# Generated by Django 5.2.8 on 2025-11-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
        ),
    ]
